// Copyright 2026 TPT Solutions. Dual-licensed MIT OR Apache-2.0.
// Generates dist/sw.js after `vite build`: a minimal cache-first Service
// Worker (spec §5 "Custom Minimal SW Generator"). Deliberately hand-rolled --
// no Workbox, no runtime routing logic, ~2KB of essential behaviour:
//   install  -> precache the hashed build output + app shell
//   fetch    -> cache-first for same-origin GET, offline navigations fall
//               back to the cached index.html shell
//   activate -> purge stale caches
//   sync     -> relay Background Sync ("tpt-sync") to an open client
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = fileURLToPath(new URL('.', import.meta.url))
const distDir = join(scriptDir, '..', 'dist')

function walk(dir, base = '') {
  const entries = []
  for (const name of readdirSync(dir)) {
    const absolute = join(dir, name)
    const relative = base ? `${base}/${name}` : name
    if (statSync(absolute).isDirectory()) {
      entries.push(...walk(absolute, relative))
    } else if (!relative.endsWith('.map') && relative !== 'sw.js') {
      entries.push(relative)
    }
  }
  return entries
}

const files = walk(distDir).sort()
const version = createHash('sha256')
  .update(files.map((file) => `${file}:${statSync(join(distDir, file)).size}`).join('\n'))
  .digest('hex')
  .slice(0, 12)

const precache = ['/', ...files.map((file) => `/${file}`)]

const worker = `/* tpt-pwa service worker -- generated by scripts/generate-sw.mjs, do not edit. */
const CACHE = 'tpt-pwa-${version}'
const PRECACHE = ${JSON.stringify(precache)}

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  event.respondWith(
    caches.match(request).then((cached) =>
      cached ||
      (request.mode === 'navigate'
        ? caches.match('/index.html').then((shell) => shell || fetch(request))
        : fetch(request).then((response) => {
            if (response.ok) {
              const copy = response.clone()
              caches.open(CACHE).then((cache) => cache.put(request, copy))
            }
            return response
          })),
    ),
  )
})

self.addEventListener('sync', (event) => {
  if (event.tag !== 'tpt-sync') return
  event.waitUntil(
    self.clients.matchAll({ includeUncontrolled: true }).then((clients) => {
      for (const client of clients) client.postMessage({ type: 'tpt-sync' })
    }),
  )
})
`

writeFileSync(join(distDir, 'sw.js'), worker)
const kb = (Buffer.byteLength(worker) / 1024).toFixed(2)
console.log(`generate-sw: dist/sw.js (${kb} KB, ${files.length} precached assets, rev ${version})`)
