// @ts-nocheck
// Node build script: runs outside the app's TS program (no node types there).
// Copyright 2026 TPT Solutions. Dual-licensed MIT OR Apache-2.0.
// Generates dist/sw.js after `vite build`: a minimal cache-first Service
// Worker (spec §5 "Custom Minimal SW Generator"). Deliberately hand-rolled --
// no Workbox, no runtime routing logic, ~2KB of essential behaviour:
//   install  -> precache the hashed build output + app shell
//   fetch    -> cache-first for same-origin GET, offline navigations fall
//               back to the cached index.html shell
//   activate -> purge stale caches
//   sync     -> relay Background Sync ("tpt-sync") to an open client
// Updates: a revised build gets a new content-hash cache name, but the worker
// never skipWaiting()s mid-session (that swaps code under a running UI) --
// it announces the waiting update and the user applies it from the app chip.
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

/**
 * An asset manifest entry: repo-relative path plus its bytes.
 * @typedef {{ path: string, content: string | Buffer }} SwAsset
 */

/**
 * Build the worker source from the asset manifest. Exported for tests: the
 * revision hash covers file CONTENTS (not names/sizes), so a rebuild that
 * changes a bundle always produces a new cache name -- and a rebuild that
 * changes nothing reuses it.
 * @param {SwAsset[]} assets
 * @returns {string}
 */
export function buildWorker(assets) {
  const files = [...assets].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
  const version = createHash('sha256')
    .update(files.map((file) => `${file.path}:${createHash('sha256').update(file.content).digest('hex')}`).join('\n'))
    .digest('hex')
    .slice(0, 12)

  const precache = ['/', ...files.map((file) => `/${file.path}`)]

  return `/* tpt-pwa service worker -- generated by scripts/generate-sw.mjs, do not edit. */
const CACHE = 'tpt-pwa-${version}'
const PRECACHE = ${JSON.stringify(precache)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() =>
        // No skipWaiting() here: the old worker keeps controlling open pages
        // until the user accepts the update from the app's UI.
        self.clients.matchAll({ includeUncontrolled: true }).then((clients) => {
          for (const client of clients) client.postMessage({ type: 'tpt-sw-update' })
        }),
      ),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'tpt-sw-skip-waiting') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  // Never satisfy the worker's own script from a cache (and never cache it):
  // the browser's HTTP-level update check must see the real bytes.
  if (url.pathname === '/sw.js') return
  event.respondWith(
    caches.match(request).then((cached) =>
      cached ||
      (request.mode === 'navigate'
        ? caches.match('/index.html').then((shell) => shell || fetch(request))
        : fetch(request).then((response) => {
            if (response.ok) {
              const copy = response.clone()
              caches.open(CACHE).then((cache) => cache.put(request, copy))
            }
            return response
          })),
    ),
  )
})

self.addEventListener('sync', (event) => {
  if (event.tag !== 'tpt-sync') return
  event.waitUntil(
    self.clients.matchAll({ includeUncontrolled: true }).then((clients) => {
      for (const client of clients) client.postMessage({ type: 'tpt-sync' })
    }),
  )
})
`
}

function main() {
  const scriptDir = fileURLToPath(new URL('.', import.meta.url))
  const distDir = join(scriptDir, '..', 'dist')

  const files = []
  for (const relative of walk(distDir)) {
    if (relative === 'sw.js') continue
    files.push({ path: relative, content: readFileSync(join(distDir, relative)) })
  }

  const worker = buildWorker(files)
  writeFileSync(join(distDir, 'sw.js'), worker)
  const kb = (Buffer.byteLength(worker) / 1024).toFixed(2)
  console.log(`generate-sw: dist/sw.js (${kb} KB, ${files.length} precached assets)`)
}

function walk(dir, base = '') {
  const entries = []
  for (const name of readdirSync(dir)) {
    const absolute = join(dir, name)
    const relative = base ? `${base}/${name}` : name
    if (statSync(absolute).isDirectory()) {
      entries.push(...walk(absolute, relative))
    } else if (!relative.endsWith('.map')) {
      entries.push(relative)
    }
  }
  return entries
}

// Only run the generator when executed directly: the test suite imports
// buildWorker() and must not depend on a dist/ existing.
if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main()
}
